services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-dev}
    ports:
      - "8000:80"
    volumes:
      - ./api:/app
    environment:
      - REDIS_URL=${REDIS_URL}
      - MERCURE_JWT_SECRET=${MERCURE_PUBLISHER_SECRET}
      - MERCURE_URL=${MERCURE_URL}
      - MERCURE_PUBLIC_URL=${MERCURE_PUBLIC_URL}

  william:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    environment:
      - APP_ENV=worker
      - REDIS_URL=${REDIS_URL}
    command: php bin/console app:danin:consume

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-dev}
    ports:
      - "3000:5173"
      - "3001:80"
    depends_on:
      - php
    volumes:
      - ./front:/app
    environment:
      VITE_API_URL: ${API_URL}
      VITE_MERCURE_URL: ${MERCURE_PUBLIC_URL}

  redis:
    image: redis:alpine

  mercure:
    image: dunglas/mercure
    ports:
      - "8090:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_PUBLISHER_SECRET}
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:3000
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  db_data:
  mercure_data:
  mercure_config:
