services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:80"
    volumes:
      - ./api:/app
    environment:
      - REDIS_URL=${REDIS_URL}
      - PHP_URL=${PHP_URL}

  william:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    environment:
      - REDIS_URL=${REDIS_URL}
      - PHP_URL=${PHP_URL}
    command: php bin/console app:danin:consume

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:5173"
    depends_on:
      - php
    volumes:
      - ./front:/app
    environment:
      VITE_API_URL: ${API_URL}

  redis:
    image: redis:alpine

volumes:
  db_data:
