api_platform:
    title: Danin
    version: 1.0.0
    formats:
      jsonld: ["application/ld+json"]
      json: ["application/json"]
    resource_class_directories:
        - '%kernel.project_dir%/src/Api/Model'
        - '%kernel.project_dir%/src/Entity'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mercure:
        include_type: true
