mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'

        game:
            url: '%env(GAME_MERCURE_URL)%'
            public_url: '%env(GAME_MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(GAME_MERCURE_JWT_SECRET)%'
                publish: '*'
