controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login

when@worker:
  notify:
    path: /notify
    methods: [POST]
    controller: App\Controller\NotifyController
