name: Build docker images

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
      - 'api/**'

env:
  REGISTRY: ghcr.io
  DOCKER_TARGET: prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        id: vars
        run: |
          REGISTRY_USER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REGISTRY_USER=$REGISTRY_USER" >> $GITHUB_ENV
          echo "IMAGE_PREFIX=${{ env.REGISTRY }}/$REGISTRY_USER/danin" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          target: ${{ env.DOCKER_TARGET }}
          tags: ${{ env.IMAGE_PREFIX }}/backend:latest
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}/api:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_PREFIX }}/api:buildcache,mode=max
          build-args: |
            PHP_VERSION=8.4.1

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          target: ${{ env.DOCKER_TARGET }}
          tags: ${{ env.IMAGE_PREFIX }}/frontend:latest
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}/frontend:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_PREFIX }}/frontend:buildcache,mode=max
          build-args: |
            VITE_API_URL=${{ secrets.API_URL }}
            VITE_MERCURE_URL=${{ secrets.MERCURE_URL }}
